### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lisaychuang**
Added link to GENERAL section, an article & talk by Chiu-Ki Chan: https://news.realm.io/news/droidcon-boston-chiu-ki-chan-how-to-be-an-android-expert/

### CODE REVIEW

**Comment by vmbrasseur** [comment]
Dang, this article really, really takes a long time to get to the speaking part. For quite a while there I didn't think this had any relevance to this repo at all, but I knew if @lisaychuang PRd it then the content must be in there somewhere, so I kept going & eventually found it.

A shame there are no header URLs so we could link directly to that section. Could you add a "(scroll down to the Speaking section)" parenthetical after the author's name, so folks have some warning that the relevant section doesn't appear immediately?

**Comment by lisaychuang** [comment]
Thanks for the feedback VM! I agree, the section related to CFP & public speaking is much further down. I'll update this request now to include a note!

**Comment by lisaychuang** [comment]
Updated!

**Comment by vmbrasseur** [comment]
:+1:

Thank you!

**Pull request merged**
